### ISSUE TITLE
Support form copy

### ISSUE THREAD

**Issue by lukpueh** [pretix/django-formset-js#2]
It would be cool to add support for form copy. I don't really know how to best achieve this. 

Currently I see two ways:
1. Add empty form and fill it with values from "form to copy" (like in my hackish-non-generic solution below).
2. Use "form to copy" as temporary template when calling ```addForm()```

Solution 1 is not so good since it has to take care of every possible form element and plugins that are attached to them explicitly.
Solution 2 is preferable, but the id incrementing is less straight forward than replacing ```__prefix__``` in the template.

Am I missing something? Any ideas would be appreciated! 

Thanks

```javascript
var copyForm = function(el) {
        //get new form and form to copy
        var $formsetPlugin = $("#formSetContainer").data("formset"),
            $oldForm = $(el).parent("[data-formset-form]"),
            $newForm = $formsetPlugin.addForm();

        //copy all selects' options 
        var $selectsOld = $oldForm.find("select");
        $newForm.find("select").each(function(idx){ 
            var optionsHTML = $selectsOld[idx].innerHTML;
            if (optionsHTML)
                $(this).html(optionsHTML);

            //Handle selectize plugin
            //XXX It would be nice if selectize did this on its own
            $selectize = $(this)[0].selectize;
            $(this).find("option[selected='selected']").each(function(idx){
                $selectize.addItem($(this).val(), true);
            });
        });

        //copy all inputs' values
        var $inputsOld = $oldForm.find("input");
        $newForm.find("input").each(function(idx){ 
            var value = $inputsOld[idx].value;
            if (value)
                $(this).val(value);
        });

        //XXX Add support for other form elements (textarea, radio, checkbox,...)
        return $newForm;
}
```

**Comment by raphaelm** [comment]
I am very sorry, but this is *not* the official repository for django-formset-js, the official one is on [bitbucket](https://bitbucket.org/tim_heap/django-formset-js) and *not* maintained by me, this is just a copy with my additional patches because the original author respons very slowly. Maybe you still should post your question over there.

Just a quick thought on your code: jQuery has a ``.clone()`` method, maybe this could simplify things?

**Comment by lukpueh** [comment]
Oops sorry, somehow missed the *"Fork of.."* subheading. :)
Cheers
